import type { i18n as I18n } from 'i18next';

const LEGACY_ZH_TO_EN: Record<string, string> = {
  '工作台': 'Dashboard',
  '项目管理': 'Projects',
  '项目详情': 'Project Detail',
  '创建新项目': 'Create New Project',
  '编辑项目': 'Edit Project',
  '知识库': 'Knowledge Base',
  '资源中心': 'Resources',
  '元器件库': 'Component Library',
  '元器件数据库': 'Component Database',
  '电路案例': 'Circuit Cases',
  '电路案例库': 'Circuit Case Library',
  '用户设置': 'User Settings',
  '个人中心': 'Profile',
  '欢迎回来，张工程师': 'Welcome back, Engineer Zhang',
  '快速入口': 'Quick Access',
  '开始新的电路设计项目': 'Start a new circuit design project',
  '查看历史项目': 'View Project History',
  '管理和查看已有的项目': 'Manage and review existing projects',
  '浏览知识库': 'Browse Knowledge Base',
  '探索元器件和电路案例': 'Explore components and circuit cases',
  '元器件查询': 'Component Search',
  '搜索和查看元器件信息': 'Search and inspect component details',
  '项目概览': 'Project Overview',
  '查看全部': 'View All',
  '总项目数': 'Total Projects',
  '进行中': 'In Progress',
  '已完成': 'Completed',
  '方案生成中': 'Generating Solution',
  'AI生成方案': 'AI Generated Solutions',
  '最近项目': 'Recent Projects',
  '项目名称': 'Project Name',
  '状态': 'Status',
  '创建时间': 'Created At',
  '操作': 'Actions',
  '系统状态': 'System Status',
  '正常': 'Normal',
  'AI模型状态': 'AI Model Status',
  '模型版本': 'Model Version',
  '响应时间': 'Response Time',
  '今日处理': 'Processed Today',
  '次': 'times',
  '知识库状态': 'Knowledge Base Status',
  '元器件数量': 'Components',
  '最后更新': 'Last Updated',
  '系统性能': 'System Performance',
  'CPU使用率': 'CPU Usage',
  '内存使用': 'Memory Usage',
  '在线用户': 'Online Users',
  '全部状态': 'All Statuses',
  '草稿': 'Draft',
  '生成中': 'Generating',
  '已归档': 'Archived',
  '编辑': 'Edit',
  '项目': 'Project',
  '此操作不可撤销': 'This action cannot be undone',
  '确定要删除这个项目吗': 'Delete this project?',
  '先创建一个项目，或者从模块工作流拼一个系统': 'Create a project first, or assemble a system from workflow modules',
  '搜索项目名称 / 描述 / 需求...': 'Search project name / description / requirements...',
  '确定要删除这个项目吗？此操作不可撤销。': 'Delete this project? This action cannot be undone.',
  '暂无项目': 'No projects yet',
  '先创建一个项目，或者从模块工作流拼一个系统。': 'Create a project first, or assemble a system from workflow modules.',
  '工作流': 'Workflow',
  '更新时间': 'Updated At',
  '模块': 'module',
  '连接': 'connection',
  '查看': 'View',
  '删除': 'Delete',
  '登录': 'Log in',
  '邮箱地址': 'Email',
  '请输入邮箱地址': 'Enter your email',
  '密码': 'Password',
  '请输入密码': 'Enter your password',
  '记住我': 'Remember me',
  '忘记密码': 'Forgot password',
  '立即登录': 'Sign in now',
  '注册账号': 'Create account',
  '保存更改': 'Save Changes',
  '保存中...': 'Saving...',
  '基本资料': 'Basic Profile',
  '公司': 'Company',
  '职位': 'Role',
  '个人简介': 'Bio',
  '修改密码': 'Change Password',
  '当前密码': 'Current Password',
  '新密码': 'New Password',
  '确认密码': 'Confirm Password',
  '通知偏好': 'Notification Preferences',
  '设置已保存': 'Settings saved',
  '成功': 'Success',
  '提示': 'Info',
  '错误': 'Error',
  '请选择': 'Please select',
  '搜索案例名称、关键词...': 'Search case name, keywords...',
  '全部领域': 'All Domains',
  '消费电子': 'Consumer Electronics',
  '工业控制': 'Industrial Control',
  '汽车电子': 'Automotive Electronics',
  '医疗电子': 'Medical Electronics',
  '物联网': 'IoT',
  '电源管理': 'Power Management',
  '全部复杂度': 'All Complexity',
  '简单': 'Simple',
  '中等': 'Medium',
  '复杂': 'Complex',
  '搜索中...': 'Searching...',
  '搜索': 'Search',
  '共': 'Total',
  '个案例': 'cases',
  '显示第': 'Showing',
  '条，共': 'to',
  '条记录': 'records',
  '每页显示': 'Per page',
  '案例详情': 'Case Detail',
  '案例名称': 'Case Name',
  '应用领域': 'Application Domain',
  '复杂度': 'Complexity',
  '案例描述': 'Case Description',
  '主要元器件': 'Key Components',
  '相关文件': 'Related Files',
  '加载中...': 'Loading...',
  '应用到项目': 'Apply to Project',
  '元器件型号': 'Component Model',
  '类型': 'Type',
  '制造商': 'Manufacturer',
  '封装': 'Package',
  '单价': 'Unit Price',
  '元器件列表': 'Component List',
  '全选': 'Select All',
  '批量删除': 'Batch Delete',
  '未找到相关元器件': 'No components found',
  '请尝试调整搜索条件或关键词': 'Try adjusting filters or keywords',
  '显示': 'Showing',
  '条': 'items',
  '还没有可用项目，请先创建项目': 'No available projects. Create one first.',
  '项目不存在或已被删除': 'Project does not exist or has been removed.',
  '该元器件已存在于项目中': 'This component already exists in the project.',
  '选择项目': 'Select Project',
  '请完整填写': 'Please complete all required fields',
  '还没有模块，先从上方添加。': 'No modules yet. Add from above first.',
  '添加模块': 'Add Module',
  '添加连接': 'Add Connection',
  '来源': 'Source',
  '目标': 'Target',
  '选择模块': 'Select Module',
  '选择端口': 'Select Port',
  '连接列表': 'Connection List',
  '校验结果': 'Validation Result',
  '暂无问题': 'No issues',
  '一键添加': 'Add with one click',
  '温馨提示': 'Tips',
  '开始生成方案': 'Start Generating',
  '电路设计需求': 'Circuit Design Requirements',
  '项目基本信息': 'Project Basic Information',
  '项目描述': 'Project Description',
  '详细需求描述': 'Detailed Requirements',
  '上传参考图像': 'Upload Reference Image',
  '点击上传或拖拽图像到此处': 'Click to upload or drag image here',
  '关闭': 'Close',
  '知识库 - PCBTool.AI': 'Knowledge Base - PCBTool.AI',
  '元器件总数': 'Total Components',
  '今日更新': 'Updated Today',
  '知识库分类': 'Knowledge Categories',
  '个元器件': 'components',
  '包含各类电子元器件的详细参数、规格、价格和供应商信息，支持多维度搜索和筛选': 'Includes detailed parameters, specs, prices, and supplier info for electronic components with multi-dimensional filtering.',
  '更新频率': 'Update Frequency',
  '实时': 'Real-time',
  '涵盖各种应用场景的电路设计案例，从简单的LED控制到复杂的嵌入式系统': 'Covers circuit design cases across scenarios, from simple LED control to complex embedded systems.',
  '分类': 'Category',
  '设计指南': 'Design Guide',
  '篇文档': 'documents',
  '包含电路设计最佳实践、PCB布局技巧、信号完整性分析等专业技术文档': 'Includes best practices in circuit design, PCB layout skills, and signal integrity analysis.',
  '难度': 'Difficulty',
  '初级到高级': 'Beginner to Advanced',
  '封装库': 'Package Library',
  '种封装': 'packages',
  '提供各种元器件的PCB封装文件，支持主流EDA软件格式': 'Provides PCB footprints for components, compatible with mainstream EDA tools.',
  '格式': 'Format',
  '多种': 'Multiple',
  '技术标准': 'Technical Standards',
  '项标准': 'standards',
  '包含电子行业相关的国际标准、国家标准和行业规范': 'Includes international, national, and industry standards related to electronics.',
  '权威机构': 'Authoritative Organizations',
  '工具手册': 'Tool Manuals',
  '份手册': 'manuals',
  '主流EDA软件使用指南、调试工具使用方法等实用文档': 'Practical documents including mainstream EDA guides and debugging tool usage.',
  '软件': 'Software',
  '热门内容': 'Popular Content',
  '查看更多案例': 'View More Cases',
  '热门元器件': 'Popular Components',
  '蓝牙模块': 'Bluetooth Module',
  '热度 98%': 'Popularity 98%',
  '锂电池': 'Lithium Battery',
  '热度 85%': 'Popularity 85%',
  '温度传感器': 'Temperature Sensor',
  '热度 76%': 'Popularity 76%',
  '查看全部元器件': 'View All Components',
  '精选案例': 'Featured Cases',
  '智能家居控制板': 'Smart Home Control Board',
  '完整': 'Complete',
  '基于ESP32的智能家居控制中心，支持WiFi、蓝牙和红外控制': 'ESP32-based smart home control center supporting Wi-Fi, Bluetooth, and IR control.',
  '次浏览': 'views',
  '次下载': 'downloads',
  '环境监测节点': 'Environmental Monitoring Node',
  '集成温湿度、光照、PM2.5传感器的物联网监测设备': 'IoT monitoring device integrating temperature/humidity, light, and PM2.5 sensors.',
  '便携式电源管理': 'Portable Power Management',
  '包含锂电池充放电管理、USB输出的移动电源解决方案': 'Power bank solution with lithium battery charging/discharging management and USB output.',
  '查看全部案例': 'View All Cases',
  '最近更新': 'Recent Updates',
  '新增元器件': 'New Components',
  '新增了STM32H7系列微控制器的完整参数和封装信息': 'Added full specs and package details for STM32H7 microcontrollers.',
  '小时前': 'hours ago',
  '价格更新': 'Price Update',
  '更新了1': 'Updated 1',
  '个元器件的实时价格信息': 'components real-time pricing info',
  '新增案例': 'New Case',
  '新增了': 'Added',
  '太阳能充电控制器': 'Solar Charge Controller',
  '完整设计案例': 'complete design case',
  '天前': 'days ago',
  '主控芯片': 'MCU',
  '核心架构': 'Core Architecture',
  '主频': 'Clock Frequency',
  '工作电压': 'Operating Voltage',
  '温度范围': 'Temperature Range',
  '双核 Tensilica LX6': 'Dual-core Tensilica LX6',
  '无线': 'Wireless',
  '核心芯片': 'Core Chip',
  '数字I/O': 'Digital I/O',
  '模拟输入': 'Analog Input',
  '传感器': 'Sensor',
  '精度': 'Accuracy',
  '输出': 'Output',
  '线性电压': 'Linear Voltage',
  '灵敏度': 'Sensitivity',
  '超声波测距传感器': 'Ultrasonic Distance Sensor',
  '测距范围': 'Measurement Range',
  '接口': 'Interface',
  '电阻': 'Resistor',
  '阻值': 'Resistance',
  '功率': 'Power',
  '温度系数': 'Temp Coefficient',
  '工作温度': 'Operating Temperature',
  '电容': 'Capacitor',
  '容量': 'Capacitance',
  '电压': 'Voltage',
  '二极管': 'Diode',
  '颜色': 'Color',
  '红色': 'Red',
  '波长': 'Wavelength',
  '正向电压': 'Forward Voltage',
  '正向电流': 'Forward Current',
  '视角': 'Viewing Angle',
  '直插5mm': 'Through-hole 5mm',
  '三极管': 'Transistor',
  '集电极电流': 'Collector Current',
  '集电极-发射极电压': 'Collector-Emitter Voltage',
  '放大倍数': 'Gain',
  '集成电路': 'Integrated Circuit',
  '线性稳压器': 'Linear Regulator',
  '输出电压': 'Output Voltage',
  '输出电流': 'Output Current',
  '输入电压': 'Input Voltage',
  '全部类型': 'All Types',
  '电感': 'Inductor',
  '连接器': 'Connector',
  '全部制造商': 'All Manufacturers',
  '全部封装': 'All Packages',
  '搜索元器件型号、关键词...': 'Search component model, keywords...',
  '内容展示区域': 'Content Area',
  '表格头部': 'Table Header',
  '表格内容': 'Table Content',
  '工具栏区域': 'Toolbar Area',
  '筛选条件': 'Filters',
  '搜索框': 'Search Box',
  '电路案例库 - PCBTool.AI': 'Circuit Case Library - PCBTool.AI',
  '原理图.pdf': 'Schematic.pdf',
  '布局文件.kicad_pcb': 'Layout.kicad_pcb',
  '布局文件.kicad': 'Layout.kicad',
  '布局文件.altium': 'Layout.altium',
  '源代码.ino': 'Source.ino',
  '源代码.zip': 'Source.zip',
  '固件源代码.zip': 'FirmwareSource.zip',
  '用户手册.pdf': 'UserManual.pdf',
  '测试报告.pdf': 'TestReport.pdf',
  '医疗认证报告.pdf': 'MedicalCertificationReport.pdf',
  '系统配置图.pdf': 'SystemConfig.pdf',
  '梯形图程序.zip': 'LadderProgram.zip',
  '接线图.pdf': 'WiringDiagram.pdf',
  '清单.xlsx': 'BOM.xlsx',
  '应用领域筛选': 'Domain Filter',
  '复杂度筛选': 'Complexity Filter',
  '案例列表区域': 'Case List Area',
  '案例统计': 'Case Stats',
  '案例卡片网格': 'Case Grid',
  '分页控件': 'Pagination',
  '案例详情模态弹窗': 'Case Detail Modal',
  '模态弹窗头部': 'Modal Header',
  '模态弹窗内容': 'Modal Content',
  '模态弹窗底部': 'Modal Footer',
  '汽车CAN总线通信模块': 'Automotive CAN Bus Module',
  '心率监测医疗设备': 'Heart Rate Monitoring Medical Device',
  '蓝牙音响功放电路': 'Bluetooth Audio Amplifier Circuit',
  '工业控制模块': 'Industrial Control Module',
  '锂电池充电管理': 'Li Battery Charging Management',
  '用户设置 - PCBTool.AI': 'User Settings - PCBTool.AI',
  '账号安全': 'Account Security',
  '算力配置': 'Compute Settings',
  '设置选项': 'Settings Options',
  '设置内容显示区': 'Settings Content Area',
  '姓名': 'Name',
  '请输入您的姓名': 'Enter your name',
  '请输入您的邮箱地址': 'Enter your email address',
  '公司/组织': 'Company/Organization',
  '请输入公司或组织名称': 'Enter company or organization name',
  '请输入您的职位': 'Enter your title',
  '简要介绍您的专业背景和技能...': 'Briefly describe your background and skills...',
  '账号安全设置': 'Account Security Settings',
  '请输入当前密码': 'Enter current password',
  '请输入新密码（至少8位，包含字母和数字）': 'Enter new password (at least 8 chars with letters and numbers)',
  '确认新密码': 'Confirm New Password',
  '请再次输入新密码': 'Enter new password again',
  '登录历史': 'Login History',
  '最近登录': 'Recent Login',
  '上次登录': 'Last Login',
  '通知偏好设置': 'Notification Preferences',
  '邮件通知': 'Email Notifications',
  '项目状态更新': 'Project Status Updates',
  '当项目状态发生变化时通知': 'Notify when project status changes',
  '方案生成完成': 'Notify when solution generation finishes',
  '当AI生成电路方案完成时通知': 'Notify when AI circuit solution generation is complete',
  '系统更新': 'System Updates',
  '当系统功能更新时通知': 'Notify when system features are updated',
  '站内通知': 'In-App Notifications',
  '实时消息': 'Real-time Messages',
  '在页面上显示实时通知': 'Show real-time notifications in page',
  '声音提醒': 'Sound Alerts',
  '收到通知时播放提示音': 'Play sound when notifications arrive',
  '平台不提供算力，所有请求将使用你配置的服务': 'The platform does not provide compute. All requests use your configured provider.',
  '提供方': 'Provider',
  '选择提供方': 'Select provider',
  '模型名称': 'Model Name',
  '温度': 'Temperature',
  '测试中...': 'Testing...',
  '测试连接': 'Test Connection',
  '保存配置': 'Save Configuration',
  '成功提示消息': 'Success Message',
  '基本资料已更新': 'Basic profile updated',
  '密码已更新': 'Password updated',
  '通知偏好已更新': 'Notification preferences updated',
  '算力配置已保存': 'Compute settings saved',
  '请填写所有密码字段': 'Please fill all password fields',
  '新密码和确认密码不匹配': 'New password and confirm password do not match',
  '新密码至少需要8位字符': 'New password must be at least 8 characters',
  '请完整填写 Base URL、API Key 和模型名称': 'Please complete Base URL, API Key, and model name',
  '请求失败：': 'Request failed:',
  '连接成功': 'Connection successful',
  '连接失败': 'Connection failed',
  '取消': 'Cancel',
  '搜索按钮': 'Search Button',
  '张工程师': 'Engineer Zhang',
  '电子科技有限公司': 'Electronic Technology Co., Ltd.',
  '硬件工程师': 'Hardware Engineer',
  '年硬件开发经验，擅长嵌入式系统设计和PCB布局': 'Years of hardware development experience, specializing in embedded systems and PCB layout.',
  '在消费电子和工业控制领域有丰富经验': 'Extensive experience in consumer electronics and industrial control.',
  '设置内容区': 'Settings Content',
  '设置项列表': 'Settings Item List',
  '基本资料设置': 'Basic Profile Settings',
  '元器件数据库 - PCBTool.AI': 'Component Database - PCBTool.AI',
  '确定要删除选中的元器件吗': 'Delete selected components?',
  '删除成功': 'Deleted successfully',
  '元器件清单': 'Component List',
  '已添加到项目：': 'Added to project:',
  '单价(': 'Unit Price (',
  '查看详情': 'View Details',
  '空状态': 'Empty State',
  '分页区域': 'Pagination Area',
  '显示信息': 'Display Info',
  '每页条数选择': 'Page Size Selector',
  '分页按钮': 'Pagination Buttons',
  '元器件详情模态框': 'Component Detail Modal',
  '模态框头部': 'Modal Header',
  '模态框内容': 'Modal Body',
  '模态框底部': 'Modal Footer',
  '基本信息': 'Basic Information',
  '技术规格': 'Technical Specifications',
  '数据手册': 'Datasheet',
  '查看数据手册 (PDF)': 'View Datasheet (PDF)',
  '去创建项目': 'Go Create Project',
  '添加到项目': 'Add to Project',
  '项目选择模态框': 'Project Selection Modal',
  '请选择要将': 'Please select where to add',
  '添加到的项目：': 'to project:',
  '无描述': 'No description',
  '添加中...': 'Adding...',
  '确认添加': 'Confirm Add',
  '基于Arduino Uno的智能家居控制解决方案，支持灯光控制、窗帘控制、温度监测和远程控制功能': 'Arduino Uno-based smart home control solution with lighting, curtain, temperature monitoring, and remote control.',
  '该方案采用模块化设计，易于扩展和维护，适合初学者和DIY爱好者使用': 'This solution uses a modular design, easy to extend and maintain, suitable for beginners and DIY makers.',
  '继电器模块': 'Relay Module',
  '执行器': 'Actuator',
  '温湿度传感器': 'Temperature & Humidity Sensor',
  '高性能工业控制解决方案，基于STM32F4系列微控制器，支持多种传感器接口和通信协议': 'High-performance industrial control solution based on STM32F4, supporting multiple sensor interfaces and communication protocols.',
  '该模块设计用于恶劣工业环境，具有高可靠性和稳定性': 'Designed for harsh industrial environments with high reliability and stability.',
  '通信接口': 'Communication Interface',
  '模拟输出': 'Analog Output',
  '低功耗物联网环境监测设备，支持温湿度、PM2.5、光照等多种传感器': 'Low-power IoT environmental monitoring device supporting temperature/humidity, PM2.5, light, and more.',
  '光照传感器': 'Light Sensor',
  '安全可靠的锂电池充电解决方案，支持多种电池类型和保护功能': 'Safe and reliable Li-battery charging solution supporting multiple battery types and protections.',
  '充电管理芯片': 'Charging Management Chip',
  '保护芯片': 'Protection Chip',
  '指示灯': 'Indicator LED',
  '状态指示': 'Status Indicator',
  '符合汽车级标准的CAN总线通信解决方案，支持高可靠性数据传输': 'Automotive-grade CAN bus communication solution with high-reliability data transmission.',
  '收发器': 'Transceiver',
  '控制器': 'Controller',
  '保护器件': 'Protection Device',
  '高精度医疗级心率监测解决方案，符合相关医疗认证标准': 'High-accuracy medical-grade heart-rate monitoring solution compliant with medical certification standards.',
  '心率传感器': 'Heart Rate Sensor',
  '蓝牙MCU': 'Bluetooth MCU',
  '加速度传感器': 'Accelerometer',
  '电池': 'Battery',
  '高保真蓝牙音响解决方案，支持多种音频格式和音效处理': 'Hi-fidelity Bluetooth audio solution supporting multiple formats and sound processing.',
  '蓝牙芯片': 'Bluetooth Chip',
  '功放芯片': 'Amplifier Chip',
  '运放芯片': 'Op-Amp Chip',
  '滤波器': 'Filter',
  '音频处理': 'Audio Processing',
  '控制模块': 'Control Module',
  '工业级PLC控制解决方案，支持多种输入输出接口和通信协议': 'Industrial PLC control solution supporting multiple I/O interfaces and communication protocols.',
  '数字量I/O模块': 'Digital I/O Module',
  '模拟量输入模块': 'Analog Input Module',
  '模拟量输出模块': 'Analog Output Module',
  '搜索案例': 'Search Cases',
  '电源': 'Power',
  '主控': 'Controller',
  '温湿度': 'Temp/Humidity',
};

const ATTRS_TO_TRANSLATE = ['placeholder', 'title', 'aria-label', 'alt'] as const;

const sortedPairs = Object.entries(LEGACY_ZH_TO_EN).sort(
  (a, b) => b[0].length - a[0].length,
);

const textOriginalMap = new WeakMap<Text, string>();
const attrOriginalMap = new WeakMap<Element, Record<string, string>>();
const hasChinese = (value: string) => /[\u4e00-\u9fff]/.test(value);

function translateText(input: string, enableEnglish: boolean): string {
  if (!enableEnglish || !input) return input;
  let output = input;
  for (const [zh, en] of sortedPairs) {
    if (output.includes(zh)) output = output.split(zh).join(en);
  }
  return output;
}

function processTextNode(node: Text, enableEnglish: boolean) {
  if (!textOriginalMap.has(node)) {
    textOriginalMap.set(node, node.nodeValue ?? '');
  }
  const original = textOriginalMap.get(node) ?? '';
  if (enableEnglish) {
    node.nodeValue = translateText(original, true);
    return;
  }

  // Only restore nodes that were originally Chinese and were rewritten by us.
  if (hasChinese(original) && node.nodeValue !== original) {
    node.nodeValue = original;
  }
}

function processElementAttrs(el: Element, enableEnglish: boolean) {
  const record = attrOriginalMap.get(el) ?? {};
  for (const attr of ATTRS_TO_TRANSLATE) {
    const current = el.getAttribute(attr);
    if (current == null) continue;
    if (record[attr] == null) record[attr] = current;
    const original = record[attr];
    if (enableEnglish) {
      el.setAttribute(attr, translateText(original, true));
      continue;
    }
    if (hasChinese(original) && current !== original) {
      el.setAttribute(attr, original);
    }
  }
  attrOriginalMap.set(el, record);
}

function runTranslation(enableEnglish: boolean) {
  const body = document.body;
  if (!body) return;

  const walker = document.createTreeWalker(body, NodeFilter.SHOW_TEXT);
  let current = walker.nextNode();
  while (current) {
    const textNode = current as Text;
    const parentTag = textNode.parentElement?.tagName;
    const shouldSkip = Boolean(
      textNode.parentElement?.closest('[data-no-legacy-translate="true"]'),
    );
    if (!shouldSkip && parentTag !== 'SCRIPT' && parentTag !== 'STYLE') {
      processTextNode(textNode, enableEnglish);
    }
    current = walker.nextNode();
  }

  const elements = body.querySelectorAll('*');
  for (const el of elements) {
    if (el.closest('[data-no-legacy-translate="true"]')) continue;
    processElementAttrs(el, enableEnglish);
  }
}

export function reapplyLegacyTextTranslation(i18n: I18n, forcedLang?: string) {
  if (typeof window === 'undefined' || typeof document === 'undefined') return;
  const currentLang = (forcedLang || i18n.language || i18n.resolvedLanguage || 'en')
    .toLowerCase()
    .split('-')[0];
  runTranslation(currentLang === 'en');
}

export function installLegacyTextTranslator(i18n: I18n) {
  if (typeof window === 'undefined' || typeof document === 'undefined') return;
  const apply = (lang?: string) => {
    reapplyLegacyTextTranslation(i18n, lang);
  };

  apply();
  i18n.on('languageChanged', (lang) => {
    // Run once immediately and once after the next paint to cover async React commits.
    apply(lang);
    window.requestAnimationFrame(() => apply(lang));
  });
}
